// welcome.js - Handles RFID parsing and welcome popups for AklatBayon

// Keep focus on the hidden input field at all times so the scanner works anywhere on the page
const rfidInput = document.getElementById('rfidInput');
const scanBtn = document.getElementById('manualScanBtn');

document.addEventListener('DOMContentLoaded', () => {
    if (rfidInput) {
        rfidInput.focus();
        
        // Re-focus on blur to ensure we always capture scanner input
        rfidInput.addEventListener('blur', () => {
            setTimeout(() => {
                rfidInput.focus();
            }, 10);
        });
    }

    // Allow clicking the "Scanning..." button to focus the input manually just in case
    if (scanBtn) {
        scanBtn.addEventListener('click', () => {
            rfidInput.focus();
        });
    }
});

// A small mock database of valid users to simulate recognition
const validUsers = [
    { rfid: '0001234567', name: 'Admin User', role: 'Admin' },
    { rfid: '1234567890', name: 'John Doe', role: 'Student' },
    { rfid: '0987654321', name: 'Jane Smith', role: 'Librarian' },
    { rfid: '1122334455', name: 'Mark Taylor', role: 'Faculty' }
];

// Handles the 'Enter' key press generated by most barcode/RFID scanners
function handleRFIDSubmit(event) {
    event.preventDefault();
    
    const rfidValue = rfidInput.value.trim();
    rfidInput.value = ''; // Clear input for next scan immediately
    
    if (!rfidValue) return;

    processScan(rfidValue);
}

function processScan(rfidTag) {
    // Check if user exists in our mock data
    const user = validUsers.find(u => u.rfid === rfidTag);
    
    if (user) {
        // Log attendance to localStorage for the 'Audit/History' pages later
        logAttendance(user);
        
        // Show success welcome
        Swal.fire({
            title: `Welcome, ${user.name}!`,
            text: `Role: ${user.role} | Tap successful.`,
            icon: 'success',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true,
            toast: true,
            position: 'top',
            background: '#0f3460',
            color: '#fff'
        });
    } else {
        // Unknown RFID
        Swal.fire({
            title: 'Unrecognized ID',
            text: `Card ${rfidTag} is not registered in the system.`,
            icon: 'error',
            showConfirmButton: false,
            timer: 4000,
            timerProgressBar: true,
            toast: true,
            position: 'top',
            background: '#3a0c14', // Dark red
            color: '#fff'
        });
    }
}

function logAttendance(user) {
    const timestamp = new Date().toISOString();
    const logEntry = {
        name: user.name,
        role: user.role,
        action: 'Library Entry',
        time: timestamp
    };
    
    // Retrieve existing logs from localStorage or initialize empty array
    let attendanceLogs = JSON.parse(localStorage.getItem('aklatbayon_attendance') || '[]');
    attendanceLogs.unshift(logEntry); // Add to top
    
    // Keep only the last 100 entries to prevent localStorage bloat
    if (attendanceLogs.length > 100) {
        attendanceLogs = attendanceLogs.slice(0, 100);
    }
    
    localStorage.setItem('aklatbayon_attendance', JSON.stringify(attendanceLogs));
}
